function fixationMatrix = createFixationMatrix(...
    fixationSize, fixationWidth, backgroundColor, fixationColor)
fixationMatrix = backgroundColor * ...
    ones(fixationSize + fixationWidth);
fixationMatrix(ceil(fixationSize / 2 - fixationWidth / 2) + ...
    1:floor(fixationSize / 2 + fixationWidth / 2 + 1), :) = fixationColor;
fixationMatrix(:, ceil(fixationSize / 2 - fixationWidth / 2) + ...
    1:floor(fixationSize / 2 + fixationWidth / 2 + 1)) = fixationColor;
end
